[build]
  functions = "netlify/functions" # Indique à Netlify où trouver les fonctions
  # Si vous utilisez une version spécifique de Node.js
  # [functions]
  #   node_bundler = "esbuild"
  #   [functions.environment]
  #     NODE_VERSION = "18" # Ou la version que vous préférez

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200